import { Merriweather } from "next/font/google";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import NavbarData from "@/components/navbarData";


const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className="inter-font"> {/* Apply the inter font to the body */}
        <NavbarData />
        {children}
      </body>
    </html>
  );
}